# Generated by Django 4.2 on 2025-10-28 03:11
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='laboratoristas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo_interno', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('codigo_ingreso', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ingreso', models.CharField(max_length=10)),
                ('colesterol_total', models.CharField(max_length=20)),
                ('colesterol_hdl', models.CharField(max_length=20)),
                ('colesterol_ldl', models.CharField(max_length=20)),
                ('trigliceridos', models.CharField(max_length=20)),
                ('laboratorista', models.CharField(max_length=10)),
            ],
        ),
    ]
