# Generated by Django 5.2.7 on 2025-11-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoristas',
            name='codigo_interno',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
