# Generated by Django 5.2.7 on 2025-11-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_1', '0002_alter_laboratoristas_codigo_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='codigo_ingreso',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='documento',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
